### ISSUE TITLE
can you add command !RHP

### ISSUE THREAD

**Issue by zianti** [itZzosku/Telemetry-Discord-Bot#2]
!RHP would reply with Rippe Has Problems

**Comment by itZzosku** [comment]
68c6ab00b4f929360b12a4a174a6fad716ccce8a

**Comment by itZzosku** [comment]
Implemented in commit 68c6ab00b4f929360b12a4a174a6fad716ccce8a.

Case closed!

**Comment by itZzosku** [comment]
resolve #2
